// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7NOJQ039mH0MuSHBp_rjorpnEqtSbeJs',
    appId: '1:33608831841:web:3582b4d2dc955772afab20',
    messagingSenderId: '33608831841',
    projectId: 'ci-cd-test-54e9f',
    authDomain: 'ci-cd-test-54e9f.firebaseapp.com',
    storageBucket: 'ci-cd-test-54e9f.appspot.com',
    measurementId: 'G-PNXMW2G8K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGo_NTbs7A2QwGHba11BggFxrc3ue5xjw',
    appId: '1:33608831841:android:cf839a4e8116557fafab20',
    messagingSenderId: '33608831841',
    projectId: 'ci-cd-test-54e9f',
    storageBucket: 'ci-cd-test-54e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnOMjCHI1FPd23LkNdmWYndFrxlB0fFSs',
    appId: '1:33608831841:ios:a65b020aeb928e3eafab20',
    messagingSenderId: '33608831841',
    projectId: 'ci-cd-test-54e9f',
    storageBucket: 'ci-cd-test-54e9f.appspot.com',
    iosClientId: '33608831841-r64pikjlvn7jkodln7ndbs54nj8lcupu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciCdTesting',
  );
}
